# 
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
from . import _pyponca
from enum import StrEnum

# Dispatcher for point cloud
class PointCloud:
    def __init__(self, *args):
        self.N = 0
        self.dim = 0
        self._mangledName = "unknown"
        self._cls = object

        if len(args) == 1 or len(args) == 2:
            if args[0].ndim != 2:
                raise RuntimeError("Only 2D arrays are supported !")
            
            if len(args) == 2:
                if args[0].shape != args[1].shape:
                    raise RuntimeError("Position and normal must have the same dimension !")
            
            self.object = self._pyponcapointcloud(*args)
        else:
            raise RuntimeError("At most 2 arrays of shape (N, D) are supported")
    
    def _pyponcapointcloud(self, *args):
        mangledArray = _pyponca.internal._mangleArray(args[0])

        clsname = "PointCloud" + mangledArray + "PN"
        if clsname not in _pyponca.__dict__:
            raise NotImplementedError(f"PointCloud does not have specialization for {args[0].dtype} arrays")

        self._cls  = _pyponca.__dict__[clsname]
        self._mangledName = mangledArray + "PN"
        return self._cls(*args)
    
class KDTree:
    def __init__(self, pc, isSparse = True):
        self.N = 0
        self.dim = 0
        self._mangledName = "unknown"
        self._cls = object

        mangledArray = _pyponca.internal._mangleArray(pc)
        clsname = "KdTree" + mangledArray + "PN"
        if clsname not in _pyponca.__dict__:
            raise NotImplementedError(f"PointCloud does not have specialization for {pc[0].dtype} arrays")
        
        self._cls = _pyponca.__dict__[clsname]
        self._mangledName = mangledArray + "PN"
        self.object = self._cls(pc, isSparse)

    def __getattr__(self, name):
        return getattr(self.object, name)
        
class Filters(StrEnum):
    """
        Filter mangling
    """
    SMOOTH_WEIGHT = "SW"
    CONSTANT_WEIGHT = "CW"
    NO_WEIGHT = "NW"

# Method used by the dispatcher 
# Ctor: stores base name
def __initComputeObject(self, name: str):
    self.name = name
    self.nf = Filters.SMOOTH_WEIGHT

# Creates the object
def __createComputeObject(self, data: PointCloud):
    clsname = self.name + data._mangledName + str(self.nf)
    if clsname not in _pyponca.__dict__:
        raise NotImplementedError(f"Compute object {self.name} do not have a specialization for {data._mangledName + str(self.nf)} point clouds")
    return _pyponca.__dict__[clsname]()
    
# Dispatch computation 
def __dispatchAttach(self, data):
    # We accepts both dlpacks arrays and PointCloud but the underlying 
    # object shall only work with PointCloud
    if isinstance(data, KDTree):
        pass
    elif not isinstance(data, PointCloud):
        data = PointCloud(data)

    self.object = __createComputeObject(self, data)

    # May fail with a pretty good error message generated by nanobind 
    # if dimension or type does not match 
    self.object.setNeighborFilter(self._pos, self._radius)
    self.object.attach(data.object)

# SetNeighborFilter specialization
def __dispatchSetNeighborFilter(self, pos, radius, nf = Filters.SMOOTH_WEIGHT):
    # Stores information for further dispatch
    # We leave the __dispatchCompute function the responsibility
    # of calling setNeighborFilter, which saves codes as we do not
    # know yet if the underlying object will support these parameters
    self.nf = nf

    self._pos = pos
    self._radius = radius
    
# Create Dispatchers for Compute Objects and put them in the globals pyponca module
for co in _pyponca.ComputeObjectList:
    newco = type(co, (), {
        "__init__": lambda self: __initComputeObject(self, co),
        "object": None,  
        "attach": __dispatchAttach,
        "setNeighborFilter": __dispatchSetNeighborFilter
    })
    globals()[co] = newco