# 
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
from . import _pyponca
from enum import StrEnum


__PointName = "PN"
# Dispatcher for point cloud
class PointCloud:
    """
        Main ponintcloud object that serves as a dispatch
        class magnles the array and retrieve the corresponding
        Ponca point cloud structure
    """
    def __init__(self, *args):
        self.N = 0
        self.dim = 0
        self._mangledName = "unknown"
        self._cls = object

        if len(args) == 1 or len(args) == 2:
            if args[0].ndim != 2:
                raise RuntimeError("Only 2D arrays are supported !")
            
            if len(args) == 2:
                if args[0].shape != args[1].shape:
                    raise RuntimeError("Position and normal must have the same shape !")
            
            self.object = self._pyponcapointcloud(*args)
        else:
            raise RuntimeError("At most 2 arrays of shape (N, D) are supported")
    
    def _pyponcapointcloud(self, *args):
        mangledArray = _pyponca.internal._mangleArray(args[0])

        clsname = "PointCloud" + mangledArray + __PointName
        if clsname not in _pyponca.__dict__:
            raise NotImplementedError(f"PointCloud does not have specialization for {args[0].dtype} arrays")

        self._cls  = _pyponca.__dict__[clsname]
        self._mangledName = mangledArray + __PointName
        return self._cls(*args)
    
class KDTree:
    """
        Main kdtree object that serves as a dispatch
        class magnles the array and retrieve the corresponding
        Ponca kdtree structure
    """

    def __init__(self, pc, isSparse = True):
        self.N = 0
        self.dim = 0
        self._mangledName = "unknown"
        self._cls = object

        mangledArray = _pyponca.internal._mangleArray(pc)
        clsname = "KdTree" + mangledArray + __PointName
        if clsname not in _pyponca.__dict__:
            raise NotImplementedError(f"PointCloud does not have specialization for {pc[0].dtype} arrays")
        
        self._cls = _pyponca.__dict__[clsname]
        self._mangledName = mangledArray + __PointName
        self.object = self._cls(pc, isSparse)

    def __getattr__(self, name):
        return getattr(self.object, name)
        
class Filters(StrEnum):
    """
        Filter mangling mapping
    """
    SMOOTH_WEIGHT = "SW"
    CONSTANT_WEIGHT = "CW"
    NO_WEIGHT = "NW"

# Following methods are dispatch functions

def __initComputeObject(self, name: str):
    """
        Ctor of to-be-dispatch compute object
    """
    self.name = name
    self.nf = Filters.SMOOTH_WEIGHT

# Creates the object
def __createComputeObject(self, data):
    """
        Helper function to dispatch to the correct underlying class
    """
    clsname = self.name + data._mangledName + str(self.nf)
    if clsname not in _pyponca.__dict__:
        raise NotImplementedError(f"Compute object {self.name} do not have a specialization for {data._mangledName + str(self.nf)} point clouds")
    return _pyponca.__dict__[clsname]()
    
def __dispatchAttach(self, data):
    """
        Dispatch the attach function to the correct class
    """
    if isinstance(data, KDTree):
        pass
    elif not isinstance(data, PointCloud):
        # Convert array to pointcloud !
        data = PointCloud(data)

    self.object = __createComputeObject(self, data)

    # May fail with a pretty good error message generated by nanobind 
    # if dimension or type does not match 
    self.object.setNeighborFilter(self._pos, self._radius)
    self.object.attach(data.object)

def __dispatchSetNeighborFilter(self, pos, radius, nf = Filters.SMOOTH_WEIGHT):
    """
        Dispatch the setNeighborFilter call. Also accept the neighbor filter
        as input
    """
    # Stores information for further dispatch
    # We leave the __dispatchCompute function the responsibility
    # of calling setNeighborFilter, which saves codes as we do not
    # know yet if the underlying object will support these parameters
    self.nf = nf

    self._pos = pos
    self._radius = radius

def __dispatchgetattr(self, name):
    """
        Dynamic way to handle capability-specific functions. 
        When a method is required, it is fowarded to the 
        corresponding object
    """
    return getattr(self.object, name)

# Dynamically create object based on what was exposed by the binding. 
for co in _pyponca.ComputeObjectList:
    newco = type(co, (), {
        "__init__": lambda self: __initComputeObject(self, co),
        "attach": __dispatchAttach,
        "setNeighborFilter": __dispatchSetNeighborFilter,
        # Dynamically find the function within the subobject
        "__getattr__": __dispatchgetattr
    })

    # Register the new class within the pyponca namespace
    globals()[co] = newco
