# 
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
from . import _pyponca

# Dispatcher for point cloud
class PointCloud:
    def __init__(self, *args):
        self.N = 0
        self.dim = 0
        self._mangledName = "unknown"
        self._cls = object

        if len(args) == 1:
            self.object = self._pyponcapointcloud(args[0])
        else:
            raise RuntimeError("Only point normal with (N, 2*D) dimension is supported")
    
    def _pyponcapointcloud(self, array):
        self.N = array.shape[0]
        self.dim = array.shape[1] // 2

        # Allow to obtain a contiguous n-d array from the data
        # this is necessary so that it is not mistaken with a
        # point cloud of dimension 2n
        mangledArray = _pyponca.internal._mangleArray(array[0, 0:(2*self.dim)].reshape((2, self.dim)))

        clsname = "PointCloud" + mangledArray
        if clsname not in _pyponca.__dict__:
            raise NotImplementedError(f"PointCloud does not have specialization for {array.dtype()} arrays")

        self._cls  = _pyponca.__dict__[clsname]
        self._mangledName = mangledArray + self._cls.mangledName
        return self._cls(array)

# Method used by the dispatcher 

# Ctor: stores base name
def __initComputeObject(self, name: str):
    self.name = name

# Creates the object
def __createComputeObject(name: str, data: PointCloud):
    clsname = name + data._mangledName
    if clsname not in _pyponca.__dict__:
        raise NotImplementedError(f"Compute object {name} do not have a specialization for {data._mangledName} point clouds")
    return _pyponca.__dict__[clsname]()
    
# Dispatch computation 
def __dispatchCompute(self, data):
    # We accepts both dlpacks arrays and PointCloud but the underlying 
    # object shall only work with PointCloud
    if not isinstance(data, PointCloud):
        data = PointCloud(data)

    self.object = __createComputeObject(self.name, data)

    # May fail with a pretty good error message generated by nanobind 
    # if dimension or type does not match 
    self.object.setNeighborFilter(self._pos, self._radius)
    self.object.compute(data.object)

# SetNeighborFilter specialization
def __dispatchSetNeighborFilter(self, pos, radius):
    # Stores information for further dispatch
    # We leave the __dispatchCompute function the responsibility
    # of calling setNeighborFilter, which saves codes as we do not
    # know yet if the underlying object will support these parameters
    self._pos = pos
    self._radius = radius

# Create Dispatcher for Compute Objects and put it in the globals pyponca module
for co in _pyponca.ComputeObjectList:
    newco = type(co, (), {
        "__init__": lambda self: __initComputeObject(self, co),
        "object": None,  
        "compute": __dispatchCompute,
        "setNeighborFilter": __dispatchSetNeighborFilter
    })
    globals()[co] = newco
