on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Extract CHANGELOG info
        id: changelog
        shell: bash
        run: |
          CONTENT=$(awk '/^-+$/{count++; if(count==2) exit} count==1{lines++; if(lines>2) print}' CHANGELOG)
          echo "content<<EOF" >> $GITHUB_OUTPUT
          echo "$CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
      - name: Create Release
        uses: actions/create-release@v2
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.changelog.outputs.content }}
          draft:      ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') }}
          prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') }}

